---
# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Camera
- ros_topic_name: "/drone/camera/image"
  gz_topic_name: "/world/drone_world/model/drone_model/link/frame/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/drone/imu"
  gz_topic_name: "/model/drone_model/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# cmd_vel
- ros_topic_name: "/drone/cmd_vel"
  gz_topic_name: "/model/drone_model/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Odom
- ros_topic_name: "/drone/odom"
  gz_topic_name: "/model/drone_model/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Pose
- ros_topic_name: "/drone/pose"
  gz_topic_name: "/model/drone_model/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS

# Joint States
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/drone_world/model/drone_model/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS